version: '3.8'
services:
  database:
    image: mysql:8.4.0
    hostname: database
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - .:/test-app
volumes:
  db_data:
