version: '3.8'
services:
  database:
    image: mysql:8.4.0
    hostname: database
    restart: always
    env_file:
      - .env.prod
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - .:/test-app
  app:
    build: .
    platform: linux/amd64
    container_name: app
    hostname: app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
        - database
    env_file:
      - .env.prod
    volumes:
      - .:/app
volumes:
  db_data:
