  Vagrant.configure("2") do |config| 
  config.vm.box = "spox/ubuntu-arm" 
  config.vm.box_version = "1.0.0"
  config.vm.network "private_network", ip: "192.168.56.15"
  config.vm.provider "vmware_desktop" do |vmware|
  config.vm.define "manager"
  config.vm.hostname = "manager"
    vmware.gui = true
    vmware.allowlist_verified = true
   end
 end
