version: '3.8'
services:
  database:
    image: mysql:8.4.0
    hostname: database
    ports:
      - '3306:3306'
    env_file:
      - .env
    restart: always
    volumes:
      - ./volume/data:/var/lib/mysql
      - ./volume/logs:/var/log/mysql
  service_1:
    image: lethanhquang147/service_1:latest
    build:
      context: .
      dockerfile: service_1/Dockerfile
    working_dir: /usr/src/app/service_1
    env_file:
      - .env.prod
    volumes:
      - ./shared:/usr/src/app/shared
      - ./:/usr/src/app
    command: node app.js
    deploy:
      replicas: 1
      restart_policy:
        condition: none
  service_2:
    image: lethanhquang147/service_2:latest
    build:
      context: .
      dockerfile: service_2/Dockerfile
    working_dir: /usr/src/app/service_2
    env_file:
      - .env.prod
    volumes:
      - ./shared:/usr/src/app/shared
      - ./:/usr/src/app
    command: node app.js
    deploy:
      replicas: 1
      restart_policy:
        condition: none
  service_3:
    image: lethanhquang147/service_3:latest
    build:
      context: .
      dockerfile: service_3/Dockerfile
    working_dir: /usr/src/app/service_3
    env_file:
      - .env.prod
    volumes:
      - ./shared:/usr/src/app/shared
      - ./:/usr/src/app
    command: node app.js
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
  service_4:
    image: lethanhquang147/service_4:latest
    build:
      context: .
      dockerfile: service_4/Dockerfile
    working_dir: /usr/src/app/service_4
    env_file:
      - .env.prod
    volumes:
      - ./shared:/usr/src/app/shared
      - ./:/usr/src/app
    command: node app.js
    depends_on:
      - database
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  api:
    image: lethanhquang147/api:latest
    build:
      context: .
      dockerfile: api/Dockerfile
    working_dir: /usr/src/app/api
    env_file:
      - .env.prod
    ports:
      - '3000:3000'
    volumes:
      - ./shared:/usr/src/app/shared
      - ./:/usr/src/app
    command: node index.js
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - database
