version: '3.8'
services:
  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: rabbitmq:3.9.7-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
    volumes:
      - ./volume/rabbitmq/data:/var/lib/rabbitmq
      - ./volume/rabbitmq/logs:/var/log/rabbitmq
  database:
    container_name: database-mysql
    image: mysql:8.4.0
    hostname: database
    ports:
      - '3306:3306'
    env_file:
      - .env
    restart: always
    volumes:
      - ./volume/mysql/data:/var/lib/mysql
      - ./volume/mysql/logs:/var/log/mysql
